# Site settings
title: Oliver Bailey
description: "A simple webpage for myself"
baseurl: "/" # for test: remove string '/example-url' to ''
url: ""

# User settings
username: Oliver Bailey
user_title: Technical Support and Infrastructure Manager
email: publicsite@obailey.co.uk
github_username:  OliverBailey
linkedin_public_url: oliver-bailey-5687349a # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
profile_picture: https://user-images.githubusercontent.com/8653158/56837661-2010a400-6873-11e9-8a78-74c89788bb27.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: 
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: https://www.github.com/oliverbailey
      new_tab: true
      key_trigger: g
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: public_site_setup
    url: https://github.com/OliverBailey/oliverbailey.github.io
  #- name: vim-frontend
   # url: https://github.com/victorvoid/vim-frontend
  #- name: generator-capybara
    #url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']